import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import '../styles/globals.css'

import { LocomotiveProvider } from '@/contexts/LocomotiveProvider'
import LayoutContainer from '@/components/common/LayoutContainer'
import Header from '@/components/layout/Header'
import Footer from '@/components/layout/Footer'
import ScrollToTopButton from '@/components/common/ScrollToTopButton'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <LocomotiveProvider>
          <Header />
          <LayoutContainer>{children}<ScrollToTopButton /></LayoutContainer>
          <Footer />
        </LocomotiveProvider>
      </body>
    </html>
  )
}
